name: fovea3d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - pip
  - pip:
      - open3d
      - gymnasium
      - stable-baselines3[extra]
      - tensorboard
      - numpy
      - pyyaml
