# third_party/Lidar-gym/lidar_gym/config/kitti.yaml
#
# Lidar-gym environment configuration for KITTI dataset.

data_root: "../../data/KITTI"

splits:
  train: "ImageSets/train.txt"
  val:   "ImageSets/val.txt"
  test:  "ImageSets/test.txt"

lidar_sensor:
  num_beams: 64
  max_range: 120.0
  min_range: 0.0
  horizontal_fov: [-180.0, 180.0]

grid_params:
  x_min: 0.0
  x_max: 70.4
  y_min: -40.0
  y_max: 40.0
  z_min: -3.0
  z_max: 1.0
  voxel_size: [0.1, 0.1, 0.2]
