# configs/ppo_fovea.yaml
#
# PPO hyperparameters for training the foveated attention agent.

learning_rate: 3e-4
n_steps: 2048
batch_size: 1024
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
n_epochs: 10
